version:                "3"
services:
  auto:
      image: rhparker/auto
      platform: linux/amd64
      volumes:
        - .:/auto/workspace
      ports:
        - 8888:8888
      container_name: AUTOdocker